spring.application.name=1_Reports_Webapp

spring.datasource.url=jdbc:mysql://localhost:3306/real_time_projects
spring.datasource.username= root
spring.datasource.password=140301Cer061@
spring.jpa.hibernate.ddl-auto= update
spring.jpa.show-sql= true


spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp
